/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type InEuint64Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint64StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export type InEuint32Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint32StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export interface TrstItVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getVerificationHandles"
      | "hasProfile"
      | "nextVerificationId"
      | "publishVerificationResult"
      | "readVerification"
      | "submitProfile"
      | "verify"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ProfileSubmitted"
      | "VerificationPublished"
      | "VerificationRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getVerificationHandles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextVerificationId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publishVerificationResult",
    values: [
      BigNumberish,
      boolean,
      BytesLike,
      boolean,
      BytesLike,
      boolean,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "readVerification",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProfile",
    values: [InEuint64Struct, InEuint32Struct, InEuint32Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getVerificationHandles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasProfile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextVerificationId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishVerificationResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace ProfileSubmittedEvent {
  export type InputTuple = [tenant: AddressLike];
  export type OutputTuple = [tenant: string];
  export interface OutputObject {
    tenant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationPublishedEvent {
  export type InputTuple = [
    verificationId: BigNumberish,
    overallEligible: boolean
  ];
  export type OutputTuple = [verificationId: bigint, overallEligible: boolean];
  export interface OutputObject {
    verificationId: bigint;
    overallEligible: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationRequestedEvent {
  export type InputTuple = [verificationId: BigNumberish, tenant: AddressLike];
  export type OutputTuple = [verificationId: bigint, tenant: string];
  export interface OutputObject {
    verificationId: bigint;
    tenant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TrstItVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): TrstItVerifier;
  waitForDeployment(): Promise<this>;

  interface: TrstItVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getVerificationHandles: TypedContractMethod<
    [verificationId: BigNumberish],
    [
      [string, string, string, string] & {
        tenant: string;
        passSalary: string;
        passCredit: string;
        passEmployment: string;
      }
    ],
    "view"
  >;

  hasProfile: TypedContractMethod<[tenant: AddressLike], [boolean], "view">;

  nextVerificationId: TypedContractMethod<[], [bigint], "view">;

  publishVerificationResult: TypedContractMethod<
    [
      verificationId: BigNumberish,
      passSalaryPlain: boolean,
      passSalarySig: BytesLike,
      passCreditPlain: boolean,
      passCreditSig: BytesLike,
      passEmploymentPlain: boolean,
      passEmploymentSig: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  readVerification: TypedContractMethod<
    [verificationId: BigNumberish],
    [
      [string, boolean, boolean, boolean, boolean, boolean] & {
        tenant: string;
        ready: boolean;
        passSalary: boolean;
        passCredit: boolean;
        passEmployment: boolean;
        overallEligible: boolean;
      }
    ],
    "view"
  >;

  submitProfile: TypedContractMethod<
    [
      inSalary: InEuint64Struct,
      inCredit: InEuint32Struct,
      inEmployment: InEuint32Struct
    ],
    [void],
    "nonpayable"
  >;

  verify: TypedContractMethod<
    [
      minSalary: BigNumberish,
      minCredit: BigNumberish,
      minEmploymentMonths: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getVerificationHandles"
  ): TypedContractMethod<
    [verificationId: BigNumberish],
    [
      [string, string, string, string] & {
        tenant: string;
        passSalary: string;
        passCredit: string;
        passEmployment: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasProfile"
  ): TypedContractMethod<[tenant: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextVerificationId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "publishVerificationResult"
  ): TypedContractMethod<
    [
      verificationId: BigNumberish,
      passSalaryPlain: boolean,
      passSalarySig: BytesLike,
      passCreditPlain: boolean,
      passCreditSig: BytesLike,
      passEmploymentPlain: boolean,
      passEmploymentSig: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "readVerification"
  ): TypedContractMethod<
    [verificationId: BigNumberish],
    [
      [string, boolean, boolean, boolean, boolean, boolean] & {
        tenant: string;
        ready: boolean;
        passSalary: boolean;
        passCredit: boolean;
        passEmployment: boolean;
        overallEligible: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitProfile"
  ): TypedContractMethod<
    [
      inSalary: InEuint64Struct,
      inCredit: InEuint32Struct,
      inEmployment: InEuint32Struct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [
      minSalary: BigNumberish,
      minCredit: BigNumberish,
      minEmploymentMonths: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "ProfileSubmitted"
  ): TypedContractEvent<
    ProfileSubmittedEvent.InputTuple,
    ProfileSubmittedEvent.OutputTuple,
    ProfileSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationPublished"
  ): TypedContractEvent<
    VerificationPublishedEvent.InputTuple,
    VerificationPublishedEvent.OutputTuple,
    VerificationPublishedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationRequested"
  ): TypedContractEvent<
    VerificationRequestedEvent.InputTuple,
    VerificationRequestedEvent.OutputTuple,
    VerificationRequestedEvent.OutputObject
  >;

  filters: {
    "ProfileSubmitted(address)": TypedContractEvent<
      ProfileSubmittedEvent.InputTuple,
      ProfileSubmittedEvent.OutputTuple,
      ProfileSubmittedEvent.OutputObject
    >;
    ProfileSubmitted: TypedContractEvent<
      ProfileSubmittedEvent.InputTuple,
      ProfileSubmittedEvent.OutputTuple,
      ProfileSubmittedEvent.OutputObject
    >;

    "VerificationPublished(uint256,bool)": TypedContractEvent<
      VerificationPublishedEvent.InputTuple,
      VerificationPublishedEvent.OutputTuple,
      VerificationPublishedEvent.OutputObject
    >;
    VerificationPublished: TypedContractEvent<
      VerificationPublishedEvent.InputTuple,
      VerificationPublishedEvent.OutputTuple,
      VerificationPublishedEvent.OutputObject
    >;

    "VerificationRequested(uint256,address)": TypedContractEvent<
      VerificationRequestedEvent.InputTuple,
      VerificationRequestedEvent.OutputTuple,
      VerificationRequestedEvent.OutputObject
    >;
    VerificationRequested: TypedContractEvent<
      VerificationRequestedEvent.InputTuple,
      VerificationRequestedEvent.OutputTuple,
      VerificationRequestedEvent.OutputObject
    >;
  };
}
